### ISSUE TITLE
Extend wavelength region

### ISSUE THREAD

**Issue by DeLaRiva** [aphalo/ggspectra#3]
Hi,

first thanks a lot for your nice package. I'd like to use it but it seems it is quite tailored to "biology" as the range of light is emphasized to the visible range. I'm a particle physicist working with gamma radiation and I'm quite sure this package would also be a total fit to our field, just for a different wavelength region.

For example, at the moment I have a data set which looks as follows:

```
> df
    Intensity     w.length
1 0.007920915 1.239842e-11
2 0.018415817 1.033202e-11
3 0.018204427 8.856014e-12
4 0.019472768 7.749012e-12
5 0.027356379 6.888011e-12
(...)
55 0.033984084 9.840016e-13
56 0.028997762 9.686266e-13
57 0.025404128 9.537246e-13
58 0.021474758 9.392742e-13
59 0.015220095 9.116485e-13
60 0.004799801 8.856014e-13
```

but I'm always receiving the following error when trying to convert this data to a spct data type:

```
Error in check_spct.generic_spct(x) : 
  Negative or zero 'w.length' values found: aborting!
```

When using higher values it's working. Thus, I would like to ask you whether it is (somehow) possible to allow also such small values as they are common for particle / atomic physics. Maybe a little option (like "atomic physics = True") which puts an offset to these values would already help in case R doesn't allow such small values.  Some other plot features would also be great to pick up specific domain knowledge like "this region is UV-C, x-ray, gamma,.." and some activation energies/wave lengths and stuff like this.
Thanks a lot already in advance!

**Comment by aphalo** [comment]
Hi,
Obviously a use case I did not think of! Thanks!
The answer is yes, I was too careful about testing for off-range values. However did you realize that wavelength should be expressed in nanometres rather than metres?
The shortest wavelength in the data you are trying to import is nearly 1e-20 metres.
What is the shortest wavelength expressed nanometres that you think should be accepted as different from zero?
I could use zero but I prefer to ensure that rounding errors in previous computations yielding zero trigger an error as zero.
The test is hard coded, but can easily changed. If you suggest a suitable limit I can.update code here in GitHub for tomorrow.

**Comment by aphalo** [comment]
Hi again,
The check is done in package 'photobioloy' rather than 'ggspectra'. I have edited the code used for the test and pushed it to the 'photobiology' repository at https://github.com/aphalo/photobiology. It will take some weeks before I submit a new version to CRAN, but meanwhile you can intsall 'photobiology' from GitHub. Please, let me know if the change of the test from `< 1` nm  to `< 1e-20` nm solves the problem or not.

**Comment by DeLaRiva** [comment]
> Hi, Obviously a use case I did not think of! Thanks! The answer is yes, I was too careful about testing for off-range values. However did you realize that wavelength should be expressed in nanometres rather than metres? The shortest wavelength in the data you are trying to import is nearly 1e-20 metres. What is the shortest wavelength expressed nanometres that you think should be accepted as different from zero? I could use zero but I prefer to ensure that rounding errors in previous computations yielding zero trigger an error as zero. The test is hard coded, but can easily changed. If you suggest a suitable limit I can.update code here in GitHub for tomorrow.

Hi Aphalo,
firstly, thanks a lot for the fast response and the already implemented feature as well. I'll try it asap.
I converted the units wrongly in my data, that's why I ended up with so small wavelengths. Sorry for the confusion. I'd think the smallest wavelength that makes physically sense is 10e-15, which is probably already quite the lower bound. If that's doable, that's fine, otherwise 10e-12 would probably be sufficient enough.

I've also seen some nice-looking features like adding the colors of the visible range to the plot which makes to plot very vivid which I like a lot. Would you mind adding such nice things for (the) other wavelength regions as well? Just in general, I'd help defining useful regions or energies in general.

**Comment by aphalo** [comment]
@DeLaRiva Suggestions are always welcome. How fast I will implement them depends on how much work it takes. The wavelength test is implemented in a seprate function, so I had only to change one number. The "colour.guide" bar is based human vision. The "colour boxes" also have their colour based on human vision. If I understand you correctly, you would like to include a colour bar with _false colours_ outside the range of true human colour vision. I think this would be rather easy to implement, but being arbitrary false colours one woud need to carefully think what colours to assign to different wavelength ranges, or if gradual, how to map wavelengths to false colours. To be useful the colours should not be just a decoration but instead provide useful information to the reader of the plot.

At the moment wave number and frequency can be only displayed as secondary axes. Supporting these quantities on the main _x_  axis has been in my todo list for some time, as I know that in fields outside photobiology they are used.

**Comment by DeLaRiva** [comment]
Sure, no worries. I'll drop some features requests just right here, one by one.
The first one would be the x-axis expressed in Energy (Joule and/or eV) instead of wavelength.

And you're right about the colour bands. I have to think about what makes sense and will let you know.

It is working, btw, thanks a lot!

**Comment by aphalo** [comment]
@DeLaRiva scales for x expressed in energy (eV and J), frequency, and wavenumber are now implemented. A function for adding a secondary axis in energy (eV or J) when the main x axis is wavelength in nanometres is also implemented. There are examples of their use in the respective help pages. These are all now pushed to the main branch here. If you have time, could you test that these works as expected, and that I have not messed things up. The conversion functions are in the latest CRAN version of 'photobiology'.

**Comment by aphalo** [comment]
@DeLaRiva One obvious solution for false colours is a twist on what is used sometimes for representing colour vision of animals: using the human vision colour response but shifting the mapping of wavelenths to the wavelength range of interest. This would give a continuous scale of varying colours. Maybe less confusing would be a bar with a luminosity gradient.
